import ChatLeftNavbar from "@/components/chat/left-nav";
import { Button } from "@/components/ui/button";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Dashboard | Neuraly Ai",
  description: "Generated by create next app",
};

export default function layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* Top Navigation Bar */}
      <div className="bg-white w-full h-[72px] flex justify-start items-center gap-4 border-b-2 border-gray-200 fixed top-0 left-0 z-10">
        <div className="pl-12">
          <Link href={`/`}>
            <Image
              src="/images/logo/neuraly-logo.svg"
              height={100}
              width={140}
              alt="neuraly.ai"
            />
          </Link>
        </div>

        <div className="ml-auto pr-12 flex justify-center items-center gap-6">
          <Link href="/dashboard">
            <Button>
              <span className="font-semibold">Dashboard</span>
            </Button>
          </Link>

          <div className="flex-shrink-0">
            <Image
              src="/images/profile-photo.png"
              width={40}
              height={40}
              alt="logout"
              className="rounded-full flex-shrink-0"
            />
          </div>
        </div>
      </div>
      {/* Left Side Bar */}
      <ChatLeftNavbar />
      {/* Main Content */}
      <div className="ml-[300px] mt-[72px]">{children}</div>
    </>
  );
}
