import LeftNavbar from "@/components/dashboard/left-navbar";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Dashboard | Neuraly Ai",
  description: "Generated by create next app",
};

export default function layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {/* Top Navigation Bar */}
      <div className="bg-white w-full h-[72px] flex justify-start items-center gap-4 border-b-2 border-gray-200 fixed top-0 left-0 z-10">
        <div className="pl-12">
          <Link href={`/`}>
            <Image
              src="/images/logo/neuraly-logo.svg"
              height={100}
              width={140}
              alt="neuraly.ai"
            />
          </Link>
        </div>
      </div>
      {/* Left Side Bar */}
      <LeftNavbar />
      {/* Main Content */}
      <div className="ml-[240px] mt-[72px]">{children}</div>
    </div>
  );
}
